version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx8192m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Checking Docker Commands
          command: |
            docker -v
            containerd -v
            sudo docker ps -a
            



