version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx8192m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: "Scanning by the Sonar Tool"
          command: |
            apt-get update
            apt-get install jq
            echo "Running  the scanning ..."
            bash sonar_run.sh
#            - run:
      #          name: Docker commands
      #          command: |
      #            docker run -it --name ubuntumachine ubuntu
      # - run:
      #     name: Build and push docker image
      #     command: |
      #       docker build -t amoljp19/sonarqubedockercircleci .
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #       docker push amoljp19/sonarqubedockercircleci
      # - run:
      #     name: Start Service and Check That it’s Running
      #     command: |
      #       ifconfig
      #       docker ps
      #       docker container run -d -p 127.0.0.1:9000:9000 --name resumesendermvvm_remote_container amoljp19/resumesendermvvm_remote_image
      #       docker ps
      #       docker exec -it resumesendermvvm_remote_container curl http://127.0.0.1:9000
      # - run:
      #     name: Scanning by the Sonar Tool
      #     command: |
      #       echo "Running the scanning ..."
      #       bash sonar_run.sh

